# Generated by Django 2.2.16 on 2021-12-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211219_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirm_code',
            new_name='confirmation_code',
        ),
    ]
